### ISSUE TITLE
Questions/Concerns about thread safety of this class

### ISSUE THREAD

**Issue by jslott** [Collaborne/tomcat-remoteip-aws-valve#5]
I looked over the source code for this valve and have questions about the thread-safety:

1. In the constructor you have this:
```
		// Do an initial blocking update, and then
		updateScheduler.scheduleWithFixedDelay(new Runnable() {
			@Override
			public void run() {
				try {
					updateIpRanges();
				} catch (IOException e) {
					log.warn("Cannot update AWS IP ranges", e);
				}
			}
		}, 0, 60, TimeUnit.SECONDS);
```
However, even with an initial delay of 0, i don't believe updateIpRanges() runs in the main thread. So I'm not sure this achieves the "do an initial blocking update" as you desire. In fact, I'm not certain this belongs in the constructor, I think `startInternal` or some lifecycle method might be better, to avoid doing anything in a partially constructed object.

2. Every 60 seconds you call updateIpRanges() which invokes setTrustedProxies() in the base class. However, this method is not thread-safe, as `trustedProxies` is not volatile nor is the getter/setter protected by the same monitor. It's not so much a question of a race-condition, but the Java memory model does not guarantee the `trustedProxies` value is ever seen by the main thread.

Thanks for making this code available! I hope you find my comments useful.

**Comment by ankon** [comment]
Thanks for your comments, will look into these points!

**Comment by ankon** [comment]
I've addressed both your points, and released version 1.1.1 of this valve with the changes. Thanks again!

**Comment by jslott** [comment]
Thanks for taking a look! I really appreciate you putting this code out in the public. Looking at `RemoteIpValve`, the `invoke()` method accesses the `trustedProxies` variable directly. According to the Java memory model, if the variable is not volatile (and `trustedProxies in `RemoteIpValve` is not volatile), then both the reading and writing must be protected by the same lock.

Here's my solution:
`private volatile String awsTrustedProxies = null;`

and
```
	@Override
	public void invoke(Request request, Response response) throws IOException, ServletException {
		// The 'trustedProxies' variable in the RemoveIpValve super class is not thread-safe,
		// and the 'invoke' method accesses the variable directly (ie does not use the setter). So
		// in order for this thread to see the updated value from the background thread, we need
		// to safely copy the trusted proxies first into this thread
		setTrustedProxies(awsTrustedProxies);
		super.invoke(request, response);
	}
```
So here i copy the volatile awsTrustedProxies (which is set by the background thread in `updateIpRanges()`) into `trustedProxies` in the same thread as `invoke()`.

For completeness, I removed the constructor and added this:
```
	@Override
	protected synchronized void startInternal() throws LifecycleException {
		updateIpRanges();
		updateScheduler.scheduleWithFixedDelay(this::updateIpRanges, 60, 60, TimeUnit.SECONDS);
		super.startInternal();
	}
```

Thanks again!

**Comment by jslott** [comment]
There's another point worth mentioning, the `invoke()` method of RemoteIpValve does this:
```
                } else if (trustedProxies != null &&
                        trustedProxies.matcher(currentRemoteIp).matches()) {
```
The `invoke()` method can be invoked by any other of the request servicing threads in tomcat concurrently. This means there is a potential race condition where two different tomcat threads set the value of `trustedProxies` -- a NPE is possible here if one thread checks `trustedProxies != null` and passes, then another thread sets `trustedProxies` to null and then the first thread `trustedProxies.matcher()` throws a NPE. However unlikely this is, I believe it is possible.

I'm starting to think the best approach is to copy the `RemoteIpValve` source entirely and modify it rather than subclassing it.

**Comment by ankon** [comment]
> I'm starting to think the best approach is to copy the RemoteIpValve source entirely and modify it rather than subclassing it.

Initially I was considering this as well, but ultimately decided against it: It would require continuously monitoring the tomcat sources, and merging any changes there into the copy. It will also make it a lot less obvious what the actual goal is here: query the AWS endpoint service, calculate a RE and update a setting with it.

Your above suggestions to make the constructor pure and move activity completely into `#startInternal()` and using a separate volatile variable to update from the same thread seem reasonable (although for tracking purposes I rather do that in a separate PR/ticket). I cannot find a way for `trustedProxies` to be set to `null` though, so that looks like an impossible case.

**Comment by jslott** [comment]
Your concerns about tracking changes to the original RemoteIpValve are entirely reasonable! In any case, many thanks again.

**Comment by ankon** [comment]
I filed #6 for your suggestions, please have a look :)
